[package]
name = "fat-horses-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = "0.4.45"
domain.workspace = true
percent-encoding = "2.3.2"
rand = "0.10.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["time"] }
tracing = "0.1.44"
ulid = "3.0.0"

[dev-dependencies]
fat-horses-store = { path = "../store" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
